before_install:
  - chmod +x before_install.sh
  - ./before_install.sh
script:
  - chmod +x travis_script.sh
  - ./travis_script.sh
matrix:
  include:
  # Linux
    - os: linux
      env: FLUTTER_VERSION=stable
      language: android
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
          - add-on
          - extra
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid
    - os: linux
      env: FLUTTER_VERSION=dev
      language: android
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
          - add-on
          - extra
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid
    # OSX
    - os: osx
      env: FLUTTER_VERSION=stable
      language: generic
      osx_image: xcode10.1
    - os: osx
      env: FLUTTER_VERSION=dev
      language: generic
      osx_image: xcode10.1
cache:
  directories:
    - $HOME/.pub-cache